// lib/exportPDF.ts
// Captures the research report DOM section and exports it as a PDF
// Uses html2canvas to render the DOM to an image, then jsPDF to create the PDF

import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface ExportOptions {
  ticker: string;
  elementId: string; // the DOM element ID to capture
}

export async function exportReportToPDF({ ticker, elementId }: ExportOptions): Promise<void> {
  const element = document.getElementById(elementId);
  if (!element) {
    throw new Error('Report element not found. Please run an analysis first.');
  }

  // Capture the DOM element as a high-resolution canvas
  // scale: 2 gives retina-quality output without being too large
  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,           // allow cross-origin images
    backgroundColor: '#0a0a0a', // match our dark background
    logging: false,
    windowWidth: element.scrollWidth,
    windowHeight: element.scrollHeight,
  });

  const imgData = canvas.toDataURL('image/png');

  // A4 dimensions in mm
  const PAGE_WIDTH = 210;
  const PAGE_HEIGHT = 297;
  const MARGIN = 10; // mm margin on each side

  const usableWidth = PAGE_WIDTH - MARGIN * 2;

  // Calculate image dimensions to fit page width
  const imgWidthPx = canvas.width;
  const imgHeightPx = canvas.height;
  const ratio = imgHeightPx / imgWidthPx;
  const imgHeightMm = usableWidth * ratio;

  // Create PDF in portrait A4
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  // ── Cover metadata strip ──────────────────────────────────────
  // Dark header bar at top of first page
  pdf.setFillColor(10, 10, 10);
  pdf.rect(0, 0, PAGE_WIDTH, 18, 'F');

  pdf.setTextColor(52, 211, 153); // emerald-400
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'bold');
  pdf.text('INSTITUTIONAL RESEARCH TERMINAL', MARGIN, 7);

  pdf.setTextColor(113, 113, 122); // zinc-500
  pdf.setFontSize(7);
  pdf.setFont('helvetica', 'normal');
  pdf.text('ZERO-BIAS AI RESEARCH REPORT · NOT FINANCIAL ADVICE', MARGIN, 12);

  pdf.setTextColor(161, 161, 170);
  pdf.text(
    'Ticker: ' + ticker + '   |   Generated: ' + new Date().toLocaleString(),
    MARGIN,
    16.5
  );

  // ── Paginate the captured image ───────────────────────────────
  // If the report is taller than one A4 page, split it across multiple pages
  const contentStartY = 20; // mm — below the header strip
  const availableHeightPerPage = PAGE_HEIGHT - contentStartY - MARGIN;

  let remainingHeightMm = imgHeightMm;
  let sourceYMm = 0; // how far down the image we've printed so far

  while (remainingHeightMm > 0) {
    const sliceHeightMm = Math.min(remainingHeightMm, availableHeightPerPage);

    // Convert mm slice back to pixel coordinates for canvas slicing
    const sourceYPx = (sourceYMm / imgHeightMm) * imgHeightPx;
    const sliceHeightPx = (sliceHeightMm / imgHeightMm) * imgHeightPx;

    // Create a temporary canvas for this page slice
    const sliceCanvas = document.createElement('canvas');
    sliceCanvas.width = imgWidthPx;
    sliceCanvas.height = Math.ceil(sliceHeightPx);

    const ctx = sliceCanvas.getContext('2d');
    if (ctx) {
      ctx.drawImage(
        canvas,
        0, sourceYPx,                    // source x, y
        imgWidthPx, sliceHeightPx,       // source width, height
        0, 0,                            // dest x, y
        imgWidthPx, sliceHeightPx        // dest width, height
      );
    }

    const sliceData = sliceCanvas.toDataURL('image/png');
    pdf.addImage(
      sliceData,
      'PNG',
      MARGIN,
      sourceYMm === 0 ? contentStartY : MARGIN, // first page starts lower (below header)
      usableWidth,
      sliceHeightMm
    );

    remainingHeightMm -= sliceHeightMm;
    sourceYMm += sliceHeightMm;

    // Add a new page if there's more content
    if (remainingHeightMm > 0) {
      pdf.addPage();
      // Repeat dark header on subsequent pages
      pdf.setFillColor(10, 10, 10);
      pdf.rect(0, 0, PAGE_WIDTH, 8, 'F');
      pdf.setTextColor(52, 211, 153);
      pdf.setFontSize(7);
      pdf.setFont('helvetica', 'bold');
      pdf.text('INSTITUTIONAL RESEARCH TERMINAL · ' + ticker, MARGIN, 5.5);
    }
  }

  // ── Footer on last page ───────────────────────────────────────
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFillColor(10, 10, 10);
    pdf.rect(0, PAGE_HEIGHT - 8, PAGE_WIDTH, 8, 'F');
    pdf.setTextColor(63, 63, 70);
    pdf.setFontSize(6.5);
    pdf.setFont('helvetica', 'normal');
    pdf.text(
      'This report is generated by AI and does not constitute financial advice. Data from Finnhub & Alpha Vantage.',
      MARGIN,
      PAGE_HEIGHT - 3.5
    );
    pdf.text(
      'Page ' + i + ' of ' + pageCount,
      PAGE_WIDTH - MARGIN - 18,
      PAGE_HEIGHT - 3.5
    );
  }

  // ── Save the PDF ──────────────────────────────────────────────
  const date = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
  pdf.save('research-' + ticker + '-' + date + '.pdf');
}
